const FETCH_TODO = "FETCH_TODO"
const FETCH_TODO_FINISHED = "FETCH_TODO_FINISHED";
const FETCH_TODO_FAILED = "FETCH_TODO_FAILED";
const GET_MORE_NEWS = "GET_MORE_NEWS";
const GET_MORE_NEWS_SUCCESS = "GET_MORE_NEWS_SUCCESS";
const GET_MORE_NEWS_FAIL = "GET_MORE_NEWS_FAIL";
const GET_PREV_NEWS = "GET_PREV_NEWS";
const GET_PREV_NEWS_SUCCESS = "GET_PREV_NEWS_SUCCESS";
const GET_PREV_NEWS_FAIL = "GET_PREV_NEWS_FAIL";

export default {
    FETCH_TODO,
    FETCH_TODO_FINISHED,
    FETCH_TODO_FAILED,
    GET_MORE_NEWS,
    GET_MORE_NEWS_SUCCESS,
    GET_MORE_NEWS_FAIL,
    GET_PREV_NEWS,
    GET_PREV_NEWS_SUCCESS,
    GET_PREV_NEWS_FAIL
}
